
pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                echo "Cloning of the repository to be initiated!"
                git https://github.com/iddhawan01/datalocaltogithub.git
                echo "Cloning successfully!"    
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                cd docker-build
                echo "Docker Build to be initiated!"
                docker build -t my-first-image .
                '''
            }
        }
    }

    post {
        success {
            echo "Use Case 3: Docker image built successfully!"
        }
    }
}
